version: "3.9"

services:
  mysqldb:
    container_name: mysqldb-microservices
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - search_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
  rabbitmq:
    container_name: rabbitmq-microservices
    image: rabbitmq
    ports:
      - "5672:5672"

volumes:
  search_volume:

networks:
    springboot-mysql-net:
        driver: bridge
